apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-records-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-records-service
  template:
    metadata:
      labels:
        app: health-records-service
    spec:
      containers:
        - name: health-records-service
          image: nandana2002/health-records-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          env:
            - name: DATABASE_URL
              value: postgresql://admin:password123@postgres-records-svc:5432/db_health_records
---
apiVersion: v1
kind: Service
metadata:
  name: health-records-service-svc
spec:
  selector:
    app: health-records-service
  ports:
    - port: 8083
      targetPort: 8083
