apiVersion: v1
kind: Secret
metadata:
  name: vitacare-db-secrets
type: Opaque
stringData:
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: password123
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vitacare-db-config
data:
  USERS_DB: db_users
  APPOINTMENTS_DB: db_appointments
  RECORDS_DB: db_health_records
  PHARMACY_DB: db_pharmacy
