# ─── All Backend ClusterIP Services ───

# User Management
apiVersion: v1
kind: Service
metadata:
  name: user-management
  namespace: backend
  labels:
    app: user-management
spec:
  type: ClusterIP
  selector:
    app: user-management
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
---
# Doctor Appointment
apiVersion: v1
kind: Service
metadata:
  name: doctor-appointment
  namespace: backend
  labels:
    app: doctor-appointment
spec:
  type: ClusterIP
  selector:
    app: doctor-appointment
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
---
# Pharmacy
apiVersion: v1
kind: Service
metadata:
  name: pharmacy
  namespace: backend
  labels:
    app: pharmacy
spec:
  type: ClusterIP
  selector:
    app: pharmacy
  ports:
    - port: 5001
      targetPort: 5001
      protocol: TCP
---
# Medical Records
apiVersion: v1
kind: Service
metadata:
  name: medical-records
  namespace: backend
  labels:
    app: medical-records
spec:
  type: ClusterIP
  selector:
    app: medical-records
  ports:
    - port: 5002
      targetPort: 5002
      protocol: TCP
---
# Lab Appointment
apiVersion: v1
kind: Service
metadata:
  name: lab-appointment
  namespace: backend
  labels:
    app: lab-appointment
spec:
  type: ClusterIP
  selector:
    app: lab-appointment
  ports:
    - port: 3003
      targetPort: 3003
      protocol: TCP
---
# Ambulance Booking
apiVersion: v1
kind: Service
metadata:
  name: ambulance-booking
  namespace: backend
  labels:
    app: ambulance-booking
spec:
  type: ClusterIP
  selector:
    app: ambulance-booking
  ports:
    - port: 3004
      targetPort: 3004
      protocol: TCP
