apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: affinity-required-ds
spec:
  selector:
    matchLabels:
      app: affinity-demo
  template:
    metadata:
      labels:
        app: affinity-demo
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: disktype
                operator: In
                values:
                - ssd
      containers:
      - name: busybox
        image: busybox
        command: ["sh", "-c", "sleep 3600"]
