apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-db
  template:
    metadata:
      labels:
        app: appointment-db
    spec:
      containers:
      - name: appointment-db
        image: mysql:8
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: healthcare_root_2024
        - name: MYSQL_DATABASE
          value: appointment_db
