apiVersion: v1
kind: Pod
metadata:
  name: affinity-or
  namespace: scheduling-demo
spec:
  containers:
  - name: nginx
    image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:

        - matchExpressions:
          - key: env
            operator: In
            values:
            - prod

        - matchExpressions:
          - key: env
            operator: In
            values:
            - dev
