apiVersion: v1
kind: Pod
metadata:
  name: affinity-preferred
  namespace: scheduling-demo
spec:
  containers:
  - name: nginx
    image: nginx
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 10
        preference:
          matchExpressions:
          - key: env
            operator: In
            values:
            - staging
