apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sc-dynamic-pvc
  namespace: volume-ns
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: nfs-dynamic
  resources:
    requests:
      storage: 1Gi
