apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-static-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-pod
  template:
    metadata:
      labels:
        app: nfs-pod
    spec:
      containers:
      - name: busybox-con
        image: busybox
        command:
        - /bin/sh
        - -c
        - while true; do echo "Persistent Data" >> /data/file.txt; sleep 5; done
        volumeMounts:
        - name: nfs
          mountPath: /data
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs
